SELECT *
FROM SALES AS S
INNER JOIN CUSTOMERS AS C ON C.CUSTOMER_ID = S.CUSTOMER_ID
INNER JOIN PRODUCTS AS P ON P.PRODUCT_ID = S.PRODUCT_ID
LEFT JOIN DEALERSHIPS AS D ON D.DEALERSHIP_ID = S.DEALERSHIP_ID
ORDER BY 1;