SELECT C.*,
	P.*,
	COALESCE(S.DEALERSHIP_ID,
		'-1') AS DEALERSHIP_ID,
	CASE WHEN (P.BASE_MSRP - s.sales_amount > 500) THEN 1
	ELSE 0 END AS HIGH_SAVING
FROM SALES AS S
INNER JOIN CUSTOMERS AS C ON C.CUSTOMER_ID = S.CUSTOMER_ID
INNER JOIN PRODUCTS AS P ON P.PRODUCT_ID = S.PRODUCT_ID
LEFT JOIN DEALERSHIPS AS D ON D.DEALERSHIP_ID = S.DEALERSHIP_ID;