WITH TOTAL_DEALERSHIP_SALES AS
	(SELECT DEALERSHIP_ID,
			SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
		FROM SALES
		WHERE SALES_TRANSACTION_DATE >= '2018-01-01'
			AND SALES_TRANSACTION_DATE < '2019-01-01'
			AND CHANNEL = 'dealership'
		GROUP BY 1)
SELECT *,
	NTILE(10) OVER (ORDER BY TOTAL_SALES_AMOUNT)
FROM TOTAL_DEALERSHIP_SALES;