WITH DAILY_SALES AS
	(SELECT SALES_TRANSACTION_DATE::Date,
			SUM(SALES_AMOUNT) AS TOTAL_SALES
		FROM SALES
		GROUP BY 1)
SELECT SALES_TRANSACTION_DATE,
	TOTAL_SALES
FROM DAILY_SALES
WHERE SALES_TRANSACTION_DATE >= '2018-01-01'
	AND SALES_TRANSACTION_DATE < '2019-01-01'
ORDER BY SALES_TRANSACTION_DATE;