SELECT SUPER_EMAIL_SEQ.ID AS SUPERSET_ID,
	SUB_EMAIL_SEQ.ID AS SUBSET_ID
FROM TOP_EMAIL_SEQUENCES AS SUPER_EMAIL_SEQ
CROSS JOIN TOP_EMAIL_SEQUENCES AS SUB_EMAIL_SEQ
WHERE SUPER_EMAIL_SEQ.EMAIL_SEQUENCE @> SUB_EMAIL_SEQ.EMAIL_SEQUENCE
	AND SUPER_EMAIL_SEQ.ID != SUB_EMAIL_SEQ.ID;