DROP MATERIALIZED VIEW IF EXISTS CUSTOMER_DATA_SEARCH;


CREATE MATERIALIZED VIEW CUSTOMER_DATA_SEARCH AS
	(SELECT CUSTOMER_JSON -> 'customer_id' AS CUSTOMER_ID,
			CUSTOMER_JSON,
			TO_TSVECTOR('english',
				CUSTOMER_JSON) AS SEARCH_VECTOR
		FROM CUSTOMER_SALES);


SELECT *
FROM CUSTOMER_DATA_SEARCH
LIMIT 1;